#!/usr/bin/env python3
"""Write out/summary_table.md from the contention-replay summary.json files.

Aggregate numbers only: no module names, file paths or titles, for any corpus (the platform
row is built from out/private/platform/ and must stay anonymous). Standard library only.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ORDER = ["workers-sdk", "codex", "platform"]


def find(out_root: Path) -> list[Path]:
    found: set[Path] = set()
    for pattern in ("*/summary.json", "*/*/summary.json", "private/*/summary.json", "private/*/*/summary.json"):
        found.update(p for p in out_root.glob(pattern) if ".scratch" not in str(p))
    return sorted(found)


def pct(x: float | None, digits: int = 2) -> str:
    return "–" if x is None else f"{100 * x:.{digits}f}%"


def num(x: float | None, digits: int = 2) -> str:
    return "–" if x is None else f"{x:.{digits}f}"


def row(cells: list[str]) -> str:
    return "| " + " | ".join(cells) + " |"


def table(header: list[str], rows: list[list[str]]) -> list[str]:
    return [row(header), row(["---"] * len(header)), *(row(r) for r in rows)]


def build(summaries: list[dict]) -> str:
    summaries = sorted(summaries, key=lambda s: (ORDER.index(s["corpus"]) if s["corpus"] in ORDER else 99,
                                                 s["corpus"], s["window_size"]))
    out = ["# Contention replay: summary (step 1)", "",
           "Measured on real merge history; each row is one corpus and window W. Pair test = "
           "leave-one-out revert for every pair i < j with j - i < W (`replay.py`). Rates are over "
           "tested pairs (clean + conflict) unless noted. Generated by `table.py` from "
           "`out/**/summary.json`; aggregate numbers only.", ""]

    out += ["## Pair test (key metrics)", ""]
    out += table(
        ["corpus", "W", "changes", "pairs", "clean", "conflict", "entangled", "conflict rate", "bound¹",
         "given shared file", "after drivers²", "after drivers, strict³", "per-change collision⁴", "P(≥1 of 20)⁵",
         "max batch⁶ (mean / p50)", "top-1 / top-3 module share⁷", "module HHI⁷ (activity)", "sampling"],
        [[s["corpus"], str(s["window_size"]), str(s["changes"]), f"{s['pairs']:,}",
          pct(s["result_shares"]["clean"], 1), pct(s["result_shares"]["conflict"], 2), pct(s["result_shares"]["entangled"], 1),
          pct(s["conflict_rate"]), pct(s["conflict_rate_bound"]), pct(s["conflict_rate_given_shared_file"], 1),
          pct(s["conflict_rate_after_drivers"]), pct(s["conflict_rate_after_drivers_strict"]),
          pct(s["per_change_collision_rate"], 1), pct(s["implied_collision_prob"]["n"]["20"], 1),
          f"{num(s['max_compatible_batch']['mean'], 1)} / {s['max_compatible_batch']['p50']} of {s['window_size']}",
          f"{pct(s['module_concentration']['top1_share'], 0)} / {pct(s['module_concentration']['top3_share'], 0)}",
          f"{num(s['module_concentration']['hhi'], 3)} ({num(s['activity_concentration']['hhi'], 3)})",
          "all windows" if s["sampling"]["method"] == "all" else
          f"{s['sampling']['pair_windows']} of {s['sampling']['full_windows']} windows ({s['sampling']['method']})"]
         for s in summaries])
    out += ["",
            "1. Upper bound: entangled pairs that share a file counted as conflicts, over all non-error pairs.",
            "2. Conflicts whose conflicted files are all lockfile, changelog, snapshot or generated (README rule) removed.",
            "3. As 2, but only when every conflict is a content or binary conflict (modify/delete and rename conflicts never reach a merge driver).",
            "4. Window-base pass: share of changes, excluding each window's first, that fail to re-apply on the window base.",
            "5. Derived, not simulated: 1 − (1 − conflict rate)^(n − 1) for n = 20 concurrent changes.",
            "6. Greedy largest conflict-free subset of each full window of W changes (fewest conflicts first).",
            "7. Each conflicting pair's weight split over the modules of its conflicted files; share = pairs whose "
            "conflicted files all sit in the top-1 / top-3 modules; HHI over module weight shares, with the same HHI "
            "for change activity in brackets.", ""]

    out += ["## Overlap, drivers and authorship", ""]
    out += table(
        ["corpus", "W", "conflicts", "rate: file / module / disjoint overlap", "rate on code files⁸: file / module / disjoint",
         "dissolvable share (strict)", "P(share module)", "P(share module), code⁸", "P(share file)", "P(share file), code⁸",
         "agent–agent", "agent–human", "human–human"],
        [[s["corpus"], str(s["window_size"]), str(s["conflicts"]),
          " / ".join(pct(s["by_overlap_class"][c]["rate"], 1) for c in ("file", "module", "disjoint")),
          " / ".join(pct(s["by_overlap_class_code"][c]["rate"], 1) for c in ("file", "module", "disjoint")),
          f"{pct(s['dissolvable_share'], 1)} ({pct(s['dissolvable_share_strict'], 1)})",
          pct(s["p_share_module"], 1), pct(s["p_share_module_code"], 1), pct(s["p_share_file"], 1), pct(s["p_share_file_code"], 1),
          *(f"{pct(s['by_authorship'][k]['rate'])} (n={s['by_authorship'][k]['pairs']:,})"
            for k in ("agent-agent", "agent-human", "human-human"))]
         for s in summaries])
    out += ["", "8. Code files = files outside the dissolvable categories; overlap recomputed on them only.", ""]

    out += ["## Clustering and batching", ""]
    out += table(
        ["corpus", "W", "full windows", "conflicting pairs per window (mean / p90 / max)", "windows with a conflict",
         "max batch, after drivers (mean)", "max batch, bound (mean)", "top-1 / top-3 file share", "file HHI (activity)",
         "modules / change (mean / p90)", "files / change (mean / p90)"],
        [[s["corpus"], str(s["window_size"]), str(s["per_window_conflicts"]["windows"]),
          f"{num(s['per_window_conflicts']['mean'], 1)} / {s['per_window_conflicts']['p90']} / {s['per_window_conflicts']['max']}",
          pct(s["per_window_conflicts"]["share_with_conflict"], 0),
          num(s["max_compatible_batch_after_drivers"]["mean"], 1), num(s["max_compatible_batch_bound"]["mean"], 1),
          f"{pct(s['file_concentration']['top1_share'], 0)} / {pct(s['file_concentration']['top3_share'], 0)}",
          f"{num(s['file_concentration']['hhi'], 3)} ({num(s['activity_file_concentration']['hhi'], 4)})",
          f"{num(s['footprint']['modules_per_change']['mean'], 1)} / {s['footprint']['modules_per_change']['p90']}",
          f"{num(s['footprint']['files_per_change']['mean'], 1)} / {s['footprint']['files_per_change']['p90']}"]
         for s in summaries])
    out += [""]

    primary = [s for s in summaries if s["window_size"] == 20] or summaries
    out += ["## Window-base per-change collision rate", "",
            "Share of changes (excluding each window's first) that fail to re-apply on the base of their fixed "
            "window: \"collides with at least one concurrent predecessor\". From the W=20 runs; the pass is "
            "repeated for each window size.", ""]
    sizes = sorted({int(w) for s in primary for w in s["window_base"]})
    out += table(["corpus", *(f"W={w}" for w in sizes), "W=20 by predecessors: 1 / 5 / 10 / 19"],
                 [[s["corpus"], *(pct(s["window_base"].get(str(w), {}).get("per_change_collision_rate"), 1) for w in sizes),
                   " / ".join(pct(s["window_base"]["20"]["by_position"][p - 1]["rate"], 0) for p in (1, 5, 10, 19))
                   if "20" in s["window_base"] else "–"]
                  for s in primary])
    out += [""]

    out += ["## Implied P(at least one collision among n concurrent changes)", "",
            "Derived, not simulated: 1 − (1 − p_pair)^(n − 1), with p_pair from the pair test.", ""]
    ns = ["5", "20", "100", "1000"]
    rows = []
    for s in summaries:
        for label, key in (("raw", "implied_collision_prob"), ("after drivers", "implied_collision_prob_after_drivers"),
                           ("bound", "implied_collision_prob_bound")):
            d = s[key]
            rows.append([s["corpus"], str(s["window_size"]), label, pct(d["p_pair"]), *(pct(d["n"][n], 1) for n in ns)])
    out += table(["corpus", "W", "p_pair", "value", *(f"n={n}" for n in ns)], rows)
    out += [""]

    out += ["## Runtime", ""]
    out += table(["corpus", "W", "pairs", "window-base pass (s)", "pair test (s)", "total (s)", "jobs", "git"],
                 [[s["corpus"], str(s["window_size"]), f"{s['pairs']:,}", num(s["runtime_seconds"]["window_base"], 0),
                   num(s["runtime_seconds"]["pair_test"], 0), num(s["runtime_seconds"]["total"], 0),
                   str(s["params"]["jobs"]), s["params"]["git"].replace("git version ", "")] for s in summaries])
    out += [""]
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--out-root", default=str(HERE / "out"), help="directory holding <corpus>/summary.json files")
    ap.add_argument("-o", "--output", default=None, help="markdown file (default: <out-root>/summary_table.md)")
    a = ap.parse_args(argv)
    root = Path(a.out_root)
    summaries = [json.loads(p.read_text()) for p in find(root)]
    if not summaries:
        raise SystemExit(f"no summary.json under {root}")
    target = Path(a.output) if a.output else root / "summary_table.md"
    target.write_text(build(summaries))
    print(f"wrote {target} ({len(summaries)} summaries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
