/**
 * OIDC for Actions jobs (doc 25 §3.5; issuer library `@beanstalk/shared-oidc`): the gateway
 * mounts the issuer at `/_actions/oidc` (discovery, JWKS, the job token endpoint) and mints a
 * job's `ACTIONS_ID_TOKEN_REQUEST_URL` / `_TOKEN` when it starts. The issuer is here, not in the
 * standalone Worker, because only the control plane knows whether a job is still running
 * (`isJobActive`: its job token is unrevoked), so a request token dies with its job.
 *
 * Optional: without `OIDC_SIGNING_KEYS` and `OIDC_REQUEST_SECRET` (generated by
 * `packages/shared-oidc/scripts/oidc-keys.mjs`), jobs get no OIDC variables and the routes
 * answer 503. `OIDC_ISSUER_URL` sets the public issuer (default `<gateway>/_actions/oidc`).
 */
import type { IdTokenJob } from '@beanstalk/shared-oidc/job-identity';
import type { OidcEnvironment } from '@beanstalk/shared-oidc/issuer';
import {
  DEFAULT_ISSUER_PATH,
  OidcNotConfiguredError,
  createOidcApp,
  issuerUrlFor,
  loadOidcConfig,
  mintIdTokenRequest,
} from '@beanstalk/shared-oidc/issuer';
import { z } from 'zod';

import type { JobRow, RunRecord } from './run-store';
import { STALK_REF } from './event-payload';

export { DEFAULT_ISSUER_PATH as OIDC_PATH };

/** The OIDC secrets and issuer URL, read without declaring them (they are optional). */
export function oidcEnvironment(env: object): OidcEnvironment {
  const read = (name: string): string | undefined => {
    const value: unknown = Reflect.get(env, name);
    return typeof value === 'string' && value !== '' ? value : undefined;
  };
  const values = {
    OIDC_SIGNING_KEYS: read('OIDC_SIGNING_KEYS'),
    OIDC_REQUEST_SECRET: read('OIDC_REQUEST_SECRET'),
    OIDC_REQUEST_SECRET_PREVIOUS: read('OIDC_REQUEST_SECRET_PREVIOUS'),
    OIDC_ISSUER_URL: read('OIDC_ISSUER_URL'),
  };
  return Object.fromEntries(Object.entries(values).filter(([, value]) => value !== undefined));
}

/** The issuer's routes, for `app.mount('/_actions/oidc', …)`. */
export function oidcRoutes(env: Env): (request: Request) => Promise<Response> {
  return async (request) => {
    const app = createOidcApp((incoming) =>
      loadOidcConfig(oidcEnvironment(env), new URL(incoming.url).origin, {
        isJobActive: (jobId) => isJobActive(env.FORGE, jobId),
      }),
    );
    app.onError((error, c) =>
      error instanceof OidcNotConfiguredError
        ? c.json({ message: 'OIDC is not configured on this deployment' }, 503)
        : c.json({ message: 'internal error' }, 500),
    );
    return app.fetch(request);
  };
}

/**
 * The job's OIDC variables, or none: when OIDC is not configured, the job lacks
 * `id-token: write`, or it is an untrusted pre-land run (D4; the library decides).
 */
export async function oidcJobEnv(input: {
  readonly env: object;
  readonly publicUrl: string;
  readonly run: RunRecord;
  readonly job: JobRow;
  readonly nowMs: number;
}): Promise<Record<string, string>> {
  const environment = oidcEnvironment(input.env);
  const secret = environment.OIDC_REQUEST_SECRET;
  if (secret === undefined || environment.OIDC_SIGNING_KEYS === undefined || secret.length < 32)
    return {};
  const identity = idTokenJob(input.run, input.job);
  if (identity === null) return {};
  const previous = environment.OIDC_REQUEST_SECRET_PREVIOUS;
  const minted = await mintIdTokenRequest(identity, {
    issuerUrl: issuerUrlFor(environment, input.publicUrl),
    secrets: previous === undefined ? { current: secret } : { current: secret, previous },
    lifetimeSeconds: input.job.timeoutMinutes * 60 + 5 * 60,
    nowMs: input.nowMs,
  });
  return minted === null
    ? {}
    : { ACTIONS_ID_TOKEN_REQUEST_URL: minted.url, ACTIONS_ID_TOKEN_REQUEST_TOKEN: minted.token };
}

/** The job as the issuer sees it; null for a pre-land run (none start in the MVP). */
export function idTokenJob(run: RunRecord, job: JobRow): IdTokenJob | null {
  const { request } = run;
  const { event } = request;
  if (request.origin.kind === 'preland' || request.origin.kind === 'event') return null;
  // Automations' Beanstalk events never get identity tokens.
  if (event !== 'push' && event !== 'schedule' && event !== 'workflow_dispatch') return null;
  return {
    jobId: job.id,
    runId: request.runId,
    runNumber: request.number,
    runAttempt: 1,
    repository: {
      id: request.repo.id,
      owner: request.repo.ownerHandle,
      ownerId: request.repo.ownerId,
      name: request.repo.name,
      visibility: request.repo.visibility,
    },
    workflowPath: request.workflow.path,
    workflowName: run.workflowName,
    workflowRef: STALK_REF,
    actor: request.actor,
    actorId: request.actor,
    idTokenWrite: job.idTokenWrite,
    run: {
      kind: 'stalk',
      event,
      ref: STALK_REF,
      sha: request.sha,
    },
  };
}

const ActiveRow = z.object({ n: z.number() });

/** A job is active while it holds an unrevoked, unexpired job token. */
async function isJobActive(db: D1Database, jobId: string): Promise<boolean> {
  const row = await db
    .prepare(
      'SELECT COUNT(*) AS n FROM actions_job_tokens WHERE job_id = ? AND revoked_ms IS NULL AND expires_ms > ?',
    )
    .bind(jobId, Date.now())
    .first();
  const parsed = ActiveRow.safeParse(row);
  return parsed.success && parsed.data.n > 0;
}
