[package]
name = "shop-billing"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
shop-core = { path = "../shop-core" }
shop-config = { path = "../shop-config" }
shop-util = { path = "../shop-util" }
shop-catalog = { path = "../shop-catalog" }
shop-sales = { path = "../shop-sales" }
shop-fulfil = { path = "../shop-fulfil" }

[dev-dependencies]
shop-testkit = { path = "../shop-testkit" }
